version : "3.8"

services: 
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
          - "3000:3000"
    volumes:
      - .:/pdp-docker-graphql
    container_name: pdp-docker-graphql-app
    command: npm start